### ISSUE TITLE
Question - Does this require PHP 5.4?

### ISSUE THREAD

**Issue by daigo75** [prewk/xml-string-streamer-guzzle#2]
I was checking the code, and it looks like it could run on PHP 5.3 as well (I know that Guzzle runs on PHP 5.3). Am I missing something?

**Comment by prewk** [comment]
Hm, it's been a while since I wrote this lib, but I'm guessing Guzzle 4.\* (which I'm using) requires 5.4 perhaps?

https://github.com/guzzle/guzzle/blob/4.0.0/composer.json

Guzzle 3.\* however requires 5.3:

https://github.com/guzzle/guzzle/blob/v3.8.1/composer.json

The code required to write your own streamer is extremely thin, all it requires is this:
https://github.com/prewk/xml-string-streamer-guzzle/blob/master/src/XmlStringStreamer/Stream/Guzzle.php

So if you need it for 5.3 perhaps you could just roll out your own streamer with legacy Guzzle and use it in `xml-string-streamer` instead.

Guzzle is 5.\* btw now, so maybe it's time to update this repo :)
